title: andrewking(me)
description: andrewking(me) is hosted from Jekyll source on GitHub Pages. Browse the source code at https://github.com/andrewkingme/andrewkingme.github.io.
url: http://andrewkingme.com
timezone: Etc/UTC
markdown: kramdown
highlighter: rouge
permalink: /news/:year/:month/:day/:title/
collections:
  work:
    output: true
    permalink: /work/:path/
  hike:
    output: true
    permalink: /hike/:path/
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
sass:
  style: compressed