title: andrewking(me)
description: andrewking(me) is hosted from Jekyll source on GitHub Pages.
url: http://andrewkingme.com
timezone: Etc/UTC
markdown: kramdown
highlighter: pygments
permalink: /news/:year/:month/:day/:title/
collections:
  work:
    output: true
    permalink: /work/:path/
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
sass:
  style: compressed