title: andrewk.ing
description: andrewk.ing is hosted from Jekyll source on GitHub Pages. Browse the source code at https://github.com/andrewkingme/andrewkingme.github.io.
url: https://andrewk.ing
timezone: Etc/UTC
markdown: kramdown
highlighter: rouge
permalink: /posts/:year/:month/:day/:title/
collections:
  work:
    output: true
    permalink: /work/:path/
  hike:
    output: true
    permalink: /hike/:path/
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
sass:
  style: compressed
